# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'Code Heroes' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Code Heroes
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth', '~> 3.0'
  pod 'OAuthSwift', '~> 1.1.0'
  pod 'PKHUD', '~> 4.0'

  target 'Code HeroesTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
